name: Build doc

on:
  push:
    # Do not run the ci if the only modified
    # files are the latex document
    paths-ignore:
      - "papers/**"
  pull_request:
    paths-ignore:
      - "papers/**"
permissions:
  contents: write

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ocaml_version: ['default']
        coq_version:
          - '9.0.1'

    # Avoid running twice the action if it's triggered by a push on a PR from a branch on the repo.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name

    steps:
      - uses: actions/checkout@master
      - name: "Run coq-community/docker-coq-action@v1 with debian:10"
        uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'rocq-ck.opam'
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}
          # Explanation for the permission issue:
          # https://github.com/coq-community/docker-coq-action#permissions
          before_script: |
            startGroup "Workaround permission issue"
              sudo chown -R 1000:1000 .  # <--
            endGroup
          script: |
            startGroup "Build project"
              #opam update -y
              #./install.sh -y
              make -j 4 doc
            endGroup
          uninstall: |
            startGroup "Clean project"
              make clean
            endGroup

      - name: Upload docs
        uses: actions/upload-pages-artifact@master
        with:
          name: docs-artifact
          path: docs
      - name: Revert permissions
        # to avoid a warning at cleanup time
        if: ${{ always() }}
        run: sudo chown -R 1001:116 . # <--
      - name: Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs
